version: '3.4'

services:
  satelliteoperationsservicesoptimizer:
    image: soso2023/soso:latest
    container_name: soso-dev-container
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 7001:7001
    command: python ./Satellite_Operations_Services_Optimizer/manage.py runserver 0.0.0.0:7000
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: db-dev-container
    environment:
      MYSQL_DATABASE: 'satellite_model'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 30s
        timeout: 10s
    ports:
      - 3306:3306

  
