version: '3.4'

services:
  satelliteoperationsservicesoptimizer:
    image: satelliteoperationsservicesoptimizer
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
