# Generated by Django 4.1.5 on 2024-03-26 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroundStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groundStationId', models.CharField(max_length=50, unique=True)),
                ('stationName', models.CharField(max_length=100, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.FloatField()),
                ('stationMask', models.CharField(max_length=100)),
                ('uplinkRate', models.FloatField()),
                ('downlinkRate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageTask',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('priority', models.PositiveIntegerField()),
                ('duration', models.DurationField()),
                ('image_type', models.CharField(max_length=10)),
                ('imagingRegionLatitude', models.FloatField()),
                ('imagingRegionLongitude', models.FloatField()),
                ('achievability', models.TextField(default='{}')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('maintenance_without_outage', models.TextField(default='[]')),
                ('schedule', models.TextField(default='[]')),
                ('tle', models.TextField()),
                ('storage_capacity', models.FloatField()),
                ('capacity_used', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Outage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outageId', models.CharField(default=None, max_length=50, unique=True)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('groundStation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='outages', to='state_model.groundstation')),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='outages', to='state_model.satellite')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('priority', models.PositiveIntegerField()),
                ('duration', models.DurationField()),
                ('next_maintenance', models.CharField(max_length=100)),
                ('is_head', models.BooleanField()),
                ('min_gap', models.IntegerField()),
                ('max_gap', models.IntegerField()),
                ('payload_outage', models.BooleanField()),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='maintenance_tasks', to='state_model.satellite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroundStationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestId', models.CharField(default=None, max_length=50, unique=True)),
                ('acquisitionOfSignal', models.DateTimeField()),
                ('lossOfSignal', models.DateTimeField()),
                ('satelliteId', models.CharField(max_length=50)),
                ('groundStation', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ground_station_requests', to='state_model.groundstation')),
            ],
        ),
    ]
