# Generated by Django 4.1.5 on 2024-03-26 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state_model', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bug',
        ),
    ]
