# Generated by Django 4.1.12 on 2023-10-18 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state_model', '0002_alter_satelliteschedule_satellite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satelliteschedule',
            name='satellite',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='satelliteSchedule', to='state_model.satellite'),
        ),
    ]
