# Generated by Django 4.1.5 on 2023-10-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_model', '0006_remove_satellite_id_remove_satelliteschedule_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downlinktask',
            name='id',
        ),
        migrations.RemoveField(
            model_name='imagingtask',
            name='id',
        ),
        migrations.RemoveField(
            model_name='maintenancetask',
            name='id',
        ),
        migrations.RemoveField(
            model_name='satelliteschedule',
            name='satellite',
        ),
        migrations.AlterField(
            model_name='downlinktask',
            name='TaskID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='imagingtask',
            name='TaskID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='TaskID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
