# Generated by Django 4.1.5 on 2023-10-30 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state_model', '0007_remove_downlinktask_id_remove_imagingtask_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groundstationrequest',
            name='id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.RemoveField(
            model_name='outage',
            name='id',
        ),
        migrations.AddField(
            model_name='satelliteschedule',
            name='satellite',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='satelliteSchedule', to='state_model.satellite'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='downlinktask',
            name='TaskID',
            field=models.CharField(default=True, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='groundstation',
            name='groundStationId',
            field=models.CharField(default=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='groundstationrequest',
            name='requestId',
            field=models.CharField(default=True, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='imageId',
            field=models.CharField(default=True, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='imagingtask',
            name='TaskID',
            field=models.CharField(default=True, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='TaskID',
            field=models.CharField(default=True, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='outage',
            name='outageId',
            field=models.CharField(default=True, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='satelliteId',
            field=models.CharField(default=True, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='satelliteschedule',
            name='scheduleID',
            field=models.CharField(default=True, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
