name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      satelliteoperationsservicesoptimizer:
        image: soso2023/soso:latest
        container_name: soso-container
        build:
          context: Satellite_Operations_Services_Optimizer
          dockerfile: Satellite_Operations_Services_Optimizer/Dockerfile
        ports:
          - 8000:8000
        command: python manage.py runserver 0.0.0.0:8000
        depends_on:
          db:
            condition: service_healthy
      db:
        image: mysql:5.7
        container_name: db-container
        environment:
          MYSQL_DATABASE: 'satellite_model'
          MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        volumes:
          - ./data/mysql/db:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            interval: 30s
            timeout: 10s

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Satellite_Operations_Services_Optimizer/requirements.txt
    - name: Run Tests
      run: |
        python Satellite_Operations_Services_Optimizer/manage.py test 
