name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: 'satellite_model'
          MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        volumes:
          - /var/lib/mysql:app/Satellite_Operations_Services_Optimizer/data/mysql/db

      satelliteoperationsservicesoptimizer:
        image: soso2023/soso:latest
        ports:
          - 8000:8000



    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Satellite_Operations_Services_Optimizer/requirements.txt
    - name: Run Tests
      run: |
        python Satellite_Operations_Services_Optimizer/manage.py test 
